package com.liondance.liondance_backend.datalayer.Notification;

public enum NotificationType {
    GENERIC,
    STUDENT_REGISTRATION,
    STUDENT_CONFIRM_REGISTRATION,
    STUDENT_FIRST_VISIT,
    STUDENT_AFTER_SESSION,
    CLASS_CANCELLATION,
    EVENT_BOOKING,
    EVENT_CONFIRM_REGISTRATION,
    EVENT_STATUS_UPDATE,
    EVENT_RESCHEDULE,
    EVENT_UPDATE,
    USER_REGISTRATION,
    AUTHORIZATION,
    ADMIN_MESSAGE,
    CLIENT_FEEDBACK_SUBMISSION,
    FEEDBACK_REQUEST,
}
