server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.liondance: DEBUG
    de.flapdoodle.embed.mongo: ERROR

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.0

---

spring:
  config:
    activate:
      on-profile: docker
  autoconfigure:
    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

  data:
    mongodb:
      host: mongo
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_ROOT_USER}
      password: ${MONGO_ROOT_PASS}
      authentication-database: admin