package com.liondance.liondance_backend.utils;

import com.liondance.liondance_backend.datalayer.Course.Course;
import com.liondance.liondance_backend.datalayer.Course.CourseRepository;
import com.liondance.liondance_backend.datalayer.Event.*;
import com.liondance.liondance_backend.datalayer.User.*;
import com.liondance.liondance_backend.datalayer.common.Address;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;

@Service
public class DataLoaderService implements CommandLineRunner {

    @Autowired
    EventRepository eventRepository;

    @Autowired
    UserRepository userRepository;

    @Autowired
    CourseRepository courseRepository;

    @Override
    public void run(String... args) throws Exception {
        ArrayList<Event> events = new ArrayList<>();
        events.add(
                Event.builder()
                        .id("0c384884-8982-45f3-b631-37badc516b7d")
                        .firstName("Rio")
                        .lastName("Da Yung OG")
                        .email("rioodayungog@michigan.com")
                        .phone("516-384-7569")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.OTHER)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("I just got out of jail")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("3285f5a9-b643-406e-83c9-890271e78bce")
                        .firstName("Joshua")
                        .lastName("Block")
                        .email("joshblock@billysio.org")
                        .phone("514-846-7385")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.WEDDING)
                        .paymentMethod(PaymentMethod.CREDIT)
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("3285f5a9-b643-406e-83c9-890271e78bva")
                        .firstName("P.")
                        .lastName("Diddy")
                        .email("thediddler@diddy.org")
                        .phone("658-173-6475")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.BIRTHDAY)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("Aint no party like a Diddy party")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("3285f5a9-b123-406e-83c9-890271e78bce")
                        .firstName("Chief")
                        .lastName("Keef")
                        .email("lovesosa@threehunna.com")
                        .phone("300-284-0394")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Chiraq")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.FESTIVAL)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("bring lean")
                        .eventStatus(EventStatus.CANCELLED)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("3285f5a9-b643-406e-83c9-732481e78bce")
                        .firstName("Neymar")
                        .lastName("Jr")
                        .email("neymar@cbf.br")
                        .phone("745-663-9378")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.WEDDING)
                        .paymentMethod(PaymentMethod.CASH)
                        .eventStatus(EventStatus.CONFIRMED)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("8547f5a9-b643-406e-83c9-890271e78bce")
                        .firstName("Trannos")
                        .lastName("O.")
                        .email("trannos@trannoios.gr")
                        .phone("697-928-4576")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.BIRTHDAY)
                        .paymentMethod(PaymentMethod.CASH)
                        .eventStatus(EventStatus.CONFIRMED)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("75a74804-af57-49ce-a8c7-7211d7d0f9ee")
                        .firstName("Billy")
                        .lastName("Sio")
                        .email("billysio@icedout.org")
                        .phone("697-394-8723")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.OTHER)
                        .paymentMethod(PaymentMethod.CASH)
                        .eventStatus(EventStatus.CANCELLED)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("75a74804-af57-49ce-a8c7-7211d7d0f9dd")
                        .firstName("Thug")
                        .lastName("Slime")
                        .email("thugslime@worstrapperintheworld.org")
                        .phone("697-069-3857")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.OTHER)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("No special requests")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("75a74804-af33-12ce-a8c7-7211d7d0f9ee")
                        .firstName("Dimitris")
                        .lastName("Mitropanos")
                        .email("roza@mitropanos.gr")
                        .phone("698-374-8673")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.FESTIVAL)
                        .paymentMethod(PaymentMethod.CREDIT)
                        .specialRequest("No special requests")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("75a74804-af57-49ce-a8c7-1265d7d0f9ee")
                        .firstName("Borat")
                        .lastName("Sagdiyev")
                        .email("borat@kazakhstan.org")
                        .phone("374-956-7398")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.OTHER)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("i have chair")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e1b07c6c6-dc48-489f-aa20-0d7d6fb12448")
                        .firstName("Sarah")
                        .lastName("Smith")
                        .email("Sarah.Smith@myfunnywebsite.org")
                        .phone("123-456-7890")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.BIRTHDAY)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("No special requests")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e1b07c6c6-dc48-489f-aa20-0d7d6fb12348")
                        .firstName("Apollo")
                        .lastName("Lightning")
                        .email("apollo.lightning@skyhigh.org")
                        .phone("450-123-4567")
                        .address(Address.builder()
                                .streetAddress("42 Thunder Road")
                                .zip("H3H 3H3")
                                .state("QC")
                                .city("Brossard")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.BIRTHDAY)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("No special requests")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e2b07c6c6-dc48-489f-aa20-0d7d6fb12449")
                        .firstName("John")
                        .lastName("Doe")
                        .email("John.Doe@myfunnywebsite.org")
                        .phone("123-456-7891")
                        .address(Address.builder()
                                .streetAddress("5678 Elm St")
                                .zip("H2H 2H2")
                                .state("QC")
                                .city("Laval")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.WEDDING)
                        .paymentMethod(PaymentMethod.CREDIT)
                        .specialRequest("Vegetarian meal")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e3b07c6c6-dc48-489f-aa20-0d7d6fb12450")
                        .firstName("Alice")
                        .lastName("Johnson")
                        .email("Alice.Johnson@myfunnywebsite.org")
                        .phone("123-456-7892")
                        .address(Address.builder()
                                .streetAddress("9101 Birch Rd")
                                .zip("H3H 3H3")
                                .state("QC")
                                .city("Brossard")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z"))
                        .eventType(EventType.FESTIVAL)
                        .paymentMethod(PaymentMethod.PAYPAL)
                        .specialRequest("Projector needed")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e4b07c6c6-dc48-489f-aa20-0d7d6fb12451")
                        .firstName("Bob")
                        .lastName("Lee")
                        .email("Bob.Lee@myfunnywebsite.org")
                        .phone("123-456-7893")
                        .address(Address.builder()
                                .streetAddress("1122 Birchwood Dr")
                                .zip("H4H 4H4")
                                .state("QC")
                                .city("Longueuil")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z").plus(3, ChronoUnit.DAYS))
                        .eventType(EventType.FESTIVAL)
                        .paymentMethod(PaymentMethod.CASH)
                        .specialRequest("Whiteboard needed")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );
        events.add(
                Event.builder()
                        .id("e5b07c6c6-dc48-489f-aa20-0d7d6fb12874")
                        .firstName("Charlie")
                        .lastName("Brown")
                        .email("Charlie.Brown@myfunnywebsite.org")
                        .phone("123-456-7894")
                        .address(Address.builder()
                                .streetAddress("2205 Redwood Blvd")
                                .zip("H5H 5H5")
                                .state("QC")
                                .city("Quebec City")
                                .build())
                        .eventDateTime(Instant.parse("2029-01-01T00:00:00Z").plus(4, ChronoUnit.DAYS))
                        .eventType(EventType.WEDDING)
                        .paymentMethod(PaymentMethod.CREDIT)
                        .specialRequest("Handouts needed")
                        .eventStatus(EventStatus.PENDING)
                        .build()
        );

        ArrayList<User> students = new ArrayList<>();
        students.add(
                Student.builder()
                        .userId("eb07c6c6-dc48-489f-aa20-0d7d6fb12448")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Sarah")
                        .middleName("Jane")
                        .lastName("Smith")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("2000-01-01"))
                        .email("Sarah.Smith@myfunnywebsite.org")
                        .phone("123-456-7890")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STAFF))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b79b0c3c-2462-42a1-922d-1a20be857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Nikolaos")
                        .middleName("Georgios")
                        .lastName("Michaloliakos")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2000-01-01"))
                        .email("nikolaos.michaloliakos@goldendawn.org")
                        .phone("123-456-7890")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b69b0c3c-2462-42a1-832d-1a22ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Hawk")
                        .middleName("Doesounow")
                        .lastName("Tuah")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("hawktuah@onthatthang.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b6m3lc3c-2462-42a1-832d-1a22ke857hba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Tony")
                        .middleName("")
                        .lastName("Nearos")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("denbleko@mebatsous.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Sepolia")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("c89b0c3c-2462-42a1-933d-1a20be857abc")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Zippora")
                        .middleName("Lemony")
                        .lastName("Snickett")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1998-06-15"))
                        .email("zippora.snickett@stories.org")
                        .phone("438-999-1234")
                        .address(Address.builder()
                                .streetAddress("5678 Mystery Lane")
                                .zip("H2H 2H2")
                                .state("QC")
                                .city("Laval")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("c98b0c3c-2462-42a1-944d-1a20be857xyz")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Apollo")
                        .middleName("Dart")
                        .lastName("Lightning")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1997-03-21"))
                        .email("apollo.lightning@skyhigh.org")
                        .phone("450-123-4567")
                        .address(Address.builder()
                                .streetAddress("42 Thunder Road")
                                .zip("H3H 3H3")
                                .state("QC")
                                .city("Brossard")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("d78b0c3c-2462-42a1-955d-1a20be857def")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Jazz")
                        .middleName("Beet")
                        .lastName("Nickelback")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2001-11-11"))
                        .email("jazz.nickelback@tuneful.org")
                        .phone("514-777-8899")
                        .address(Address.builder()
                                .streetAddress("321 Harmony Ave")
                                .zip("H4H 4H4")
                                .state("QC")
                                .city("Longueuil")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("d88b0c3c-2462-42a1-966d-1a20be857ghi")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Pixel")
                        .middleName("Bit")
                        .lastName("Byte")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2002-02-02"))
                        .email("pixel.byte@techwave.org")
                        .phone("514-567-8901")
                        .address(Address.builder()
                                .streetAddress("909 Data Drive")
                                .zip("H5H 5H5")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("e98b0c3c-2462-42a1-977d-1a20be857jkl")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Echo")
                        .middleName("Silence")
                        .lastName("Noiseworth")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1996-12-12"))
                        .email("echo.noiseworth@soundscape.org")
                        .phone("438-888-9999")
                        .address(Address.builder()
                                .streetAddress("555 Quiet Street")
                                .zip("H6H 6H6")
                                .state("QC")
                                .city("Saint-Lambert")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("n01a2b3c-4567-89ab-1011-1c23de857zzz")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Kai")
                        .middleName("")
                        .lastName("Smith")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1995-01-01"))
                        .email("kai.smith@ninjago.org")
                        .phone("514-123-1234")
                        .address(Address.builder()
                                .streetAddress("777 Fire Lane")
                                .zip("H7H 7H7")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("n02a2b3c-4567-89ab-1011-1c23de857yyy")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Jay")
                        .middleName("")
                        .lastName("Walker")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1996-02-02"))
                        .email("jay.walker@ninjago.org")
                        .phone("438-234-2345")
                        .address(Address.builder()
                                .streetAddress("888 Lightning Blvd")
                                .zip("H8H 8H8")
                                .state("QC")
                                .city("Laval")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("n03a2b3c-4567-89ab-1011-1c23de857xxx")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Zane")
                        .middleName("")
                        .lastName("Julien")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1997-03-03"))
                        .email("zane.julien@ninjago.org")
                        .phone("450-345-3456")
                        .address(Address.builder()
                                .streetAddress("999 Ice St")
                                .zip("H9H 9H9")
                                .state("QC")
                                .city("Brossard")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("n04a2b3c-4567-89ab-1011-1c23de857www")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Cole")
                        .middleName("")
                        .lastName("Brookstone")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1998-04-04"))
                        .email("cole.brookstone@ninjago.org")
                        .phone("514-456-4567")
                        .address(Address.builder()
                                .streetAddress("1000 Earth Ave")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Longueuil")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("n05a2b3c-4567-89ab-1011-1c23de857vvv")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Lloyd")
                        .middleName("")
                        .lastName("Garmadon")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-05-05"))
                        .email("lloyd.garmadon@ninjago.org")
                        .phone("438-567-5678")
                        .address(Address.builder()
                                .streetAddress("2000 Green St")
                                .zip("H2H 2H2")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );

        students.add(
                Student.builder()
                        .userId("b6910jfc-2462-42a1-832d-1a22ke82k5ba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Donald")
                        .middleName("J.")
                        .lastName("Trump")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("donald@trump.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b69b0c3c-2462-42a1-832d-1a29ke857cbf")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Lilliam")
                        .middleName("")
                        .lastName("Pumpernickel")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("guccigang@guccigang.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b6k3mg3c-2462-42a1-832d-1a00ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Tim")
                        .middleName("")
                        .lastName("Robinson")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("tim@robinson.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("bl39kc3c-2462-42a1-832d-2039ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Dave")
                        .middleName("Fat")
                        .lastName("Blunts")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("icantput@downthecup.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b6992j4c-2462-42a1-832d-1a22ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("NBA")
                        .middleName("12 kids")
                        .lastName("Youngboy")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("youngboy@neverbrokeagain.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b69bj25c-2462-42a1-832d-1a22ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Michael")
                        .middleName("Gary")
                        .lastName("Scott")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("mike@scott.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b69b0c3c-1937-42a1-832d-1m2k9e857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Knee")
                        .middleName("Doesounow")
                        .lastName("Surgeon")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("hawktuah@onthatthang.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("b01j4c3c-2462-42a1-832d-1a22ke857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("John")
                        .middleName("Doesounow")
                        .lastName("Pork")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-01-01"))
                        .email("john@pork.org")
                        .phone("514-637-8400")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );

        students.add(
                Student.builder()
                        .userId("a79b0c3c-2462-42a1-922d-1a20be857cba")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("John")
                        .middleName("Doe")
                        .lastName("Smith")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2000-01-01"))
                        .email("john.doe@myfunnywebsite.org")
                        .phone("123-456-7890")
                        .address(Address.builder()
                                .streetAddress("1234 Main St")
                                .zip("H1H 1H1")
                                .state("QC")
                                .city("Montreal")
                                .build())
                        .roles(EnumSet.of(Role.STUDENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("c56a8e9d-4362-42c8-965d-2b8b98f9f4d9")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Alice")
                        .middleName("Grace")
                        .lastName("Johnson")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1998-02-15"))
                        .email("alice.johnson@webmail.com")
                        .phone("234-567-8901")
                        .address(Address.builder()
                                .streetAddress("5678 Oak Ave")
                                .zip("H2H 2H2")
                                .state("ON")
                                .city("Toronto")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("d89f1a3e-01a5-4f97-b2a3-9927555e4951")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Bob")
                        .middleName("Ray")
                        .lastName("Lee")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2001-04-22"))
                        .email("bob.lee@someplace.com")
                        .phone("345-678-9012")
                        .address(Address.builder()
                                .streetAddress("9101 Birch Rd")
                                .zip("J3J 3J3")
                                .state("BC")
                                .city("Vancouver")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("e72c3e0d-3351-4288-9a52-5b2d4f5f6e73")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Maria")
                        .middleName("Sophia")
                        .lastName("Garcia")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-06-10"))
                        .email("maria.garcia@xyz.org")
                        .phone("456-789-0123")
                        .address(Address.builder()
                                .streetAddress("1212 Maple St")
                                .zip("R4R 4R4")
                                .state("AB")
                                .city("Calgary")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("f6ac8fcb-43d1-4958-88ea-040cd379f3a1")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Charlie")
                        .middleName("Alan")
                        .lastName("Brown")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1997-08-25"))
                        .email("charlie.brown@fakeemail.com")
                        .phone("567-890-1234")
                        .address(Address.builder()
                                .streetAddress("3456 Elm St")
                                .zip("K5K 5K5")
                                .state("NS")
                                .city("Halifax")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("g98d9b28-b00e-4d8f-a9f9-7a06368f759f")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Eve")
                        .middleName("Marie")
                        .lastName("Davis")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1996-03-14"))
                        .email("eve.davis@newdomain.org")
                        .phone("678-901-2345")
                        .address(Address.builder()
                                .streetAddress("7876 Pine Ln")
                                .zip("T6T 6T6")
                                .state("MB")
                                .city("Winnipeg")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("h27d6b6c-9069-4a0f-84f3-b259ae05e98d")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("David")
                        .middleName("James")
                        .lastName("Miller")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("1995-05-05"))
                        .email("david.miller@workplace.com")
                        .phone("789-012-3456")
                        .address(Address.builder()
                                .streetAddress("1122 Birchwood Dr")
                                .zip("L7L 7L7")
                                .state("SK")
                                .city("Regina")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("i17e1c98-a276-4b2f-a85c-34ed120d1bc4")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Grace")
                        .middleName("Lynn")
                        .lastName("Wilson")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1998-09-30"))
                        .email("grace.wilson@university.com")
                        .phone("890-123-4567")
                        .address(Address.builder()
                                .streetAddress("2205 Redwood Blvd")
                                .zip("A9A 9A9")
                                .state("QC")
                                .city("Quebec City")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("j83e2a9c-332f-471b-a0a7-39b2c8d6b299")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.PENDING)
                        .firstName("Jake")
                        .middleName("Kyle")
                        .lastName("Moore")
                        .gender(Gender.MALE)
                        .dob(LocalDate.parse("2000-11-11"))
                        .email("jake.moore@cooldomain.com")
                        .phone("901-234-5678")
                        .address(Address.builder()
                                .streetAddress("4599 Cedar Ct")
                                .zip("V8V 8V8")
                                .state("PE")
                                .city("Charlottetown")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );
        students.add(
                Student.builder()
                        .userId("k14f2e01-d60e-4204-9492-f8391e0d3387")
                        .joinDate(Instant.now())
                        .registrationStatus(RegistrationStatus.ACTIVE)
                        .firstName("Sophia")
                        .middleName("Rachel")
                        .lastName("Taylor")
                        .gender(Gender.FEMALE)
                        .dob(LocalDate.parse("1999-12-20"))
                        .email("sophia.taylor@somemail.com")
                        .phone("102-345-6789")
                        .address(Address.builder()
                                .streetAddress("6789 Willow Way")
                                .zip("W3W 3W3")
                                .state("NL")
                                .city("St. John's")
                                .build())
                        .roles(EnumSet.of(Role.CLIENT))
                        .build()
        );


        List<String> userIds = new ArrayList<>();
        userIds.add("a79b0c3c-2462-42a1-922d-1a20be857cba");
        Course course = Course.builder()
                .courseId("40374c92-6c55-417e-b8bc-9dfb38740255")
                .name("Martial Arts")
                .userIds(userIds)
                .startTime(LocalTime.parse("10:00", DateTimeFormatter.ofPattern("HH:mm")))
                .endTime(LocalTime.NOON)
                .dayOfWeek(DayOfWeek.SUNDAY)
                .instructorId("eb07c6c6-dc48-489f-aa20-0d7d6fb12448")
                .cancelledDates(new ArrayList<>())
                .build();

        eventRepository.insert(events).subscribe();
        userRepository.insert(students).subscribe();
        courseRepository.insert(course).subscribe();
    }
}
