name: Gradle Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  liondance_be:
    environment: CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Permissions Gradle
        run: chmod +x ./gradlew
        working-directory: ./liondance-be
      
      - name: Build Gradle
        env:
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          MAIL_SMTP_HOST: ${{ secrets.MAIL_SMTP_HOST }}
          MAIL_SMTP_PASS: ${{ secrets.MAIL_SMTP_PASS }}
          MAIL_SMTP_PORT: ${{ secrets.MAIL_SMTP_PORT }}
          MAIL_SMTP_USER: ${{ secrets.MAIL_SMTP_USER }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_ROOT_PASS: ${{ secrets.MONGO_ROOT_PASS }}
          MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
          MONGO_WEB_PASS: ${{ secrets.MONGO_WEB_PASS }}
          MONGO_WEB_USER: ${{ secrets.MONGO_WEB_USER }}
          OKTA_AUDIENCE: ${{ secrets.OKTA_AUDIENCE }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          OKTA_ISSUER: ${{ secrets.OKTA_ISSUER }}
          OKTA_REDIRECT_URI: ${{ secrets.OKTA_REDIRECT_URI }}
          SERVER_ROOT_DOMAIN: ${{ secrets.SERVER_ROOT_DOMAIN }}
        run: ./gradlew clean build
        working-directory: ./liondance-be

      - name: Archive coverage data
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data
          path: ./liondance-be/build/reports

      - name: JaCoCo PR Comment
        uses: madrapps/jacoco-report@v1.5
        with:
          paths: ${{ github.workspace }}/liondance-be/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Jacoco Coverage Report
          update-comment: true
