name: Playwright Tests
on:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install yarn
        run: npm install -g yarn
      - name: Reconfigure node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: liondance-fe/yarn.lock
      - name: Install deps
        run: yarn
        working-directory: ./liondance-fe
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
        working-directory: ./liondance-fe
      - name: Wait for deployment
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          frontend="${FRONTEND_URL/:\/\//://${{ github.event.number }}.}"
          backend="${BACKEND_URL/:\/\//://${{ github.event.number }}.}"

          echo "BACKEND_URL_NEW=$backend" >> $GITHUB_ENV

          echo $frontend
          echo $backend
          timeout 180 bash -c '
            while [[ "$(curl -s -o /dev/null -w "%{http_code}" '$frontend')" != "200" ]] || [[ "$(curl -s -o /dev/null -w "%{http_code}" '$backend/actuator/health')" != "200" ]]; do
              sleep 5
            done
          ' || false
      - name: Run Playwright
        run: npx playwright test --workers=4 --project='chromium' --retries 1
        working-directory: ./liondance-fe
        env:
          PR_NUMBER: ${{ github.event.number }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          PLAYWRIGHT_STAFF: ${{ secrets.PLAYWRIGHT_STAFF }}
          PLAYWRIGHT_STUDENT: ${{ secrets.PLAYWRIGHT_STUDENT }}
          PLAYWRIGHT_CLIENT: ${{ secrets.PLAYWRIGHT_CLIENT }}
          PLAYWRIGHT_ANYUSER: ${{ secrets.PLAYWRIGHT_ANYUSER }}
          PLAYWRIGHT_PASS: ${{ secrets.PLAYWRIGHT_PASS }}
          BACKEND_URL: ${{ env.BACKEND_URL_NEW }}
      - name: Archive report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./liondance-fe/playwright-report/
          retention-days: 7
